<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[【info】com.lbl.baseframe.DriverFactory: 杀死chrome浏览器进程成功]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="38986" started-at="2018-03-02T02:29:07Z" finished-at="2018-03-02T02:29:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38986" started-at="2018-03-02T02:29:07Z" finished-at="2018-03-02T02:29:46Z">
      <class name="com.lbl.testcase.LoginTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.lbl.testcase.LoginTest@548a9f61]" name="SetUp" is-config="true" duration-ms="33953" started-at="2018-03-01T14:29:07Z" finished-at="2018-03-01T14:29:40Z">
          <reporter-output>
            <line>
              <![CDATA[【info】com.lbl.baseframe.DriverFactory: 杀死chrome浏览器进程成功]]>
            </line>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="SuccessLoginTest()[pri:0, instance:com.lbl.testcase.LoginTest@548a9f61]" name="SuccessLoginTest" duration-ms="1988" started-at="2018-03-01T14:29:40Z" finished-at="2018-03-01T14:29:42Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.lbl.baseframe.DriverUtils.openUrl(DriverUtils.java:30)
	at com.lbl.pages.LoginPage.<init>(LoginPage.java:12)
	at com.lbl.actions.LoginOperate.LoginSuccess(LoginOperate.java:22)
	at com.lbl.testcase.LoginTest.SuccessLoginTest(LoginTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SuccessLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.lbl.testcase.LoginTest@548a9f61]" name="tearDown" is-config="true" duration-ms="3002" started-at="2018-03-01T14:29:43Z" finished-at="2018-03-01T14:29:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.lbl.testcase.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
